#!/bin/bash
# ============================================================================
# Legal Scout — First-time Setup
# ============================================================================
# Creates .env with auto-generated secrets. Run once before first deploy.
#
# Usage: ./scripts/setup.sh
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

echo "============================================"
echo "Legal Scout — Setup"
echo "============================================"
echo ""

if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env already exists. Overwrite? (y/N)"
    read -r confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Cancelled. Edit .env manually if needed."
        exit 0
    fi
fi

# Generate secrets
JWT_SECRET=$(openssl rand -hex 32)
DB_PASS=$(openssl rand -base64 24 | tr -d '/+=')

# Ask for OpenRouter key
echo "Enter your OpenRouter API key (from https://openrouter.ai/keys):"
read -r OPENROUTER_KEY
if [ -z "$OPENROUTER_KEY" ]; then
    echo "⚠️  No key entered — you can add it later in .env"
    OPENROUTER_KEY="sk-or-v1-your-key-here"
fi

# Ask for admin email
echo ""
echo "Admin email (default: admin@legalscout.com):"
read -r ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@legalscout.com}

# Ask for admin password
echo ""
echo "Admin password (min 10 chars):"
read -rs ADMIN_PASS
if [ ${#ADMIN_PASS} -lt 10 ]; then
    echo ""
    echo "⚠️  Password too short. Using generated password:"
    ADMIN_PASS=$(openssl rand -base64 12)
    echo "  $ADMIN_PASS  (save this!)"
fi

# Write .env
cat > "$ENV_FILE" << EOF
# Generated by setup.sh on $(date)

OPENROUTER_API_KEY=$OPENROUTER_KEY

JWT_SECRET_KEY=$JWT_SECRET

ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASS

DB_USER=scout
DB_PASS=$DB_PASS
DB_DATABASE=legalscout
EOF

echo ""
echo "============================================"
echo "✅ .env created with auto-generated secrets"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. docker compose up -d --build"
echo "  2. Open http://localhost"
echo "  3. Login: $ADMIN_EMAIL / (your password)"
echo ""
